export const channels = new Map([
    ['ABC News', 'abc-news'],
    ['Associated Press', 'associated-press'],
    ['BBC News', 'bbc-news'],
    ['BBC Sport', 'bbc-sport'],
    ['Bild', 'bild'],
    ['Bloomberg', 'bloomberg'],
    ['Business Insider', 'business-insider'],
    ['CBC News', 'cbc-news'],
    ['CNBC', 'cnbc'],
    ['CNN', 'cnn'],
    ['Der Tagesspiegel', 'der-tagesspiegel'],
    ['Die Zeit', 'die-zeit'],
    ['El Mundo', 'el-mundo'],
    ['Financial Times', 'financial-times'],
    ['Focus', 'focus'],
    ['Fox News', 'fox-news'],
    ['Google News', 'google-news'],
    ['Hacker News', 'hacker-news'],
    ['Handelsblatt', 'handelsblatt'],
    ['Independent', 'independent'],
    ['La Gaceta', 'la-gaceta'],
    ['La Repubblica', 'la-repubblica'],
    ['Le Monde', 'le-monde'],
    ['Lenta', 'lenta'],
    ['Marca', 'marca'],
    ['Metro', 'metro'],
    ['Mirror', 'mirror'],
    ['MSNBC', 'msnbc'],
    ['MTV News', 'mtv-news'],
    ['National Geographic', 'national-geographic'],
    ['NBC News', 'nbc-news'],
    ['News24', 'news24'],
    ['New Scientist', 'new-scientist'],
    ['NFL News', 'nfl-news'],
    ['NHL News', 'nhl-news'],
    ['NRK', 'nrk'],
    ['Politico', 'politico'],
    ['Polygon', 'polygon'],
    ['RBC', 'rbc'],
    ['Recode', 'recode'],
    ['Reddit /r/all', 'reddit-r-all'],
    ['Reuters', 'reuters'],
    ['RT', 'rt'],
    ['RTE', 'rte'],
    ['TechRadar', 'techradar'],
    ['The Economist', 'the-economist'],
    ['The Guardian (UK)', 'the-guardian-uk'],
    ['The Hindu', 'the-hindu'],
    ['The Irish Times', 'the-irish-times'],
    ['The Jerusalem Post', 'the-jerusalem-post'],
    ['The Lad Bible', 'the-lad-bible'],
    ['The New York Times', 'the-new-york-times'],
    ['The Next Web', 'the-next-web'],
    ['The Telegraph', 'the-telegraph'],
    ['The Verge', 'the-verge'],
    ['The Wall Street Journal', 'the-wall-street-journal'],
    ['The Washington Post', 'the-washington-post'],
    ['The Washington Times', 'the-washington-times'],
    ['Time', 'time'],
    ['USA Today', 'usa-today'],
]);